import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import rateLimit from 'express-rate-limit';

import { PORT, FRONTEND_URL, IS_DEV, IS_PROD } from './config.js';
import { errorHandler, notFoundHandler } from './middleware/error.js';
import { requestLogger } from './middleware/logger.js';
import { auditMiddleware } from './middleware/audit.js';
import { requireApiKey } from './middleware/apikey.js';

import './db.js';

import authRoutes from './routes/auth.js';
import workspaceRoutes from './routes/workspaces.js';
import boardRoutes from './routes/board.js';
import columnRoutes from './routes/columns.js';
import taskRoutes from './routes/tasks.js';
import commentRoutes from './routes/comments.js';
import attachmentRoutes from './routes/attachments.js';
import checklistRoutes from './routes/checklists.js';
import activityRouter from './routes/activity.js';
import presenceRouter from './routes/presence.js';
import apiKeysRouter from './routes/api-keys.js';
import webhooksRouter from './routes/webhooks.js';
import systemRouter from './routes/system.js';
import docsRouter from './routes/docs.js';

const app = express();

// Remove fingerprinting
app.disable('x-powered-by');

// Trust proxy only in production (for accurate client IP behind reverse proxy)
if (IS_PROD) {
  app.set('trust proxy', 1);
}

// Security headers via Helmet
app.use(helmet({
      contentSecurityPolicy: {
    directives: {
      defaultSrc: ["'self'"],
      styleSrc: ["'self'", "'unsafe-inline'", "https://fonts.googleapis.com"],
      scriptSrc: ["'self'", "'unsafe-inline'"],
      scriptSrcAttr: ["'unsafe-inline'"],
      imgSrc: ["'self'", "data:", "blob:", "https:"],
      connectSrc: ["'self'"],
      fontSrc: [
        "'self'",
        "https://fonts.gstatic.com",
        "https://fonts.googleapis.com",
        "data:"
      ],
      workerSrc: ["'self'", "blob:"],
      objectSrc: ["'none'"],
      upgradeInsecureRequests: [],
    },
  },
  crossOriginEmbedderPolicy: false,
  crossOriginResourcePolicy: { policy: 'cross-origin' },
  hsts: {
    maxAge: 31536000,
    includeSubDomains: true,
    preload: true,
  },
  referrerPolicy: { policy: 'same-origin' },
}));

// CORS
app.use(cors({
  origin: IS_DEV ? true : FRONTEND_URL,
  credentials: true,
}));

// Rate limiting
app.use(rateLimit({
  windowMs: 15 * 60 * 1000,
  max: IS_DEV ? 1000 : 100,
  standardHeaders: true,
  legacyHeaders: false,
  keyGenerator: (req) => req.ip,
  message: { error: 'Too many requests, please try again later.', code: 'RATE_LIMITED' },
}));

// Stricter rate limit for auth endpoints
app.use('/api/v1/auth', rateLimit({
  windowMs: 15 * 60 * 1000,
  max: IS_DEV ? 100 : 10,
  standardHeaders: true,
  legacyHeaders: false,
  keyGenerator: (req) => req.ip,
  message: { error: 'Too many auth attempts, please try again later.', code: 'RATE_LIMITED' },
}));

// Body parsing with limits
app.use(express.json({ limit: '1mb' }));
app.use(express.urlencoded({ extended: true, limit: '1mb' }));

// Request logging
app.use(requestLogger);

// API key middleware (runs before JWT auth — sets req.userId if valid key provided)
app.use(requireApiKey);

// Audit logging middleware (captures 401/403/429 responses)
app.use(auditMiddleware);

// Health check (before auth routes)
app.use('/api', systemRouter);

// Silence Chrome DevTools probe (no-op 204)
app.get('/.well-known/appspecific/com.chrome.devtools.json', (_req, res) => {
  res.status(204).end();
});

// API routes (v1)
app.use('/api/v1/auth', authRoutes);
app.use('/api/v1/workspaces', workspaceRoutes);
app.use('/api/v1/board', boardRoutes);
app.use('/api/v1/columns', columnRoutes);
app.use('/api/v1/tasks', taskRoutes);
app.use('/api/v1', commentRoutes);
app.use('/api/v1', attachmentRoutes);
app.use('/api/v1', checklistRoutes);
app.use('/api/v1', activityRouter);
app.use('/api/v1', presenceRouter);
app.use('/api/v1', apiKeysRouter);
app.use('/api/v1', webhooksRouter);
app.use('/api/v1', systemRouter);  // /api/v1/health for the spec
app.use('/api', docsRouter);       // GET /api/docs (public), GET /api/spec (JSON)

// 404 handler
app.use(notFoundHandler);

// Global error handler
app.use(errorHandler);

const server = app.listen(PORT, () => {
  console.log(`Jokel API running on http://localhost:${PORT} (${IS_DEV ? 'development' : 'production'})`);

  // In dev, keep docs/openapi.json in sync with the registered routes so the
  // committed file always reflects current code. In production, this file is
  // expected to be regenerated by CI (`npm run openapi:generate`).
  if (IS_DEV) {
    import('./openapi/generate.js')
      .then(({ writeOpenApiJson }) => {
        try {
          writeOpenApiJson();
        } catch (err) {
          console.warn('[openapi] failed to regenerate spec:', err.message);
        }
      })
      .catch((err) => console.warn('[openapi] dev regen skipped:', err.message));
  }
});

// Connection timeouts
server.timeout = 30000;
server.keepAliveTimeout = 65000;
server.headersTimeout = 66000;

// Graceful shutdown
function shutdown(signal) {
  console.log(`\n${signal} received. Shutting down gracefully...`);
  server.close(() => {
    console.log('HTTP server closed.');
    process.exit(0);
  });
  setTimeout(() => {
    console.error('Forced shutdown after timeout.');
    process.exit(1);
  }, 10000);
}

process.on('SIGTERM', () => shutdown('SIGTERM'));
process.on('SIGINT', () => shutdown('SIGINT'));
