/** Static demo workspace — no API, no persistence. */
export const DEMO_BOARD = {
  columnOrder: ['col-todo', 'col-progress', 'col-review', 'col-done'],
  columns: {
    'col-todo': {
      id: 'col-todo',
      title: 'To Do',
      taskIds: ['task-1', 'task-2', 'task-3', 'task-4'],
    },
    'col-progress': {
      id: 'col-progress',
      title: 'In Progress',
      taskIds: ['task-5', 'task-6', 'task-7'],
    },
    'col-review': {
      id: 'col-review',
      title: 'Review',
      taskIds: ['task-8', 'task-9'],
    },
    'col-done': {
      id: 'col-done',
      title: 'Done',
      taskIds: ['task-10', 'task-11', 'task-12'],
    },
  },
  tasks: {
    'task-1': {
      id: 'task-1',
      code: 'ELV-121',
      title: 'Capture invite resend failure from workspace settings',
      priority: 'High',
      dueDate: 'May 24',
      assigneeName: 'Maya Kim',
      tags: ['workspace', 'members'],
      labels: ['is-label-a', 'is-label-b'],
      metrics: { comments: 3, attachments: 1 },
    },
    'task-2': {
      id: 'task-2',
      code: 'ELV-118',
      title: 'Tighten read-only grid for viewer role rows',
      priority: 'Medium',
      assigneeName: 'Alex Reed',
      tags: ['ui', 'permissions', 'layout'],
      checklists: { done: 2, total: 5 },
    },
    'task-3': {
      id: 'task-3',
      code: 'ELV-116',
      title: 'Document webhook signature verification',
      priority: 'Low',
      tags: ['docs', 'api'],
      metrics: { comments: 1 },
    },
    'task-4': {
      id: 'task-4',
      code: 'ELV-114',
      title: 'Stage quick-start checklist copy for first workspace',
      priority: 'Medium',
      dueDate: 'Today',
      dueStatus: 'due-today',
      assigneeName: 'Sam Taylor',
      tags: ['onboarding'],
      labels: ['is-label-c'],
    },
    'task-5': {
      id: 'task-5',
      code: 'ELV-109',
      title: 'Drag-drop pause while board filters are active',
      priority: 'Critical',
      assigneeName: 'Jordan L.',
      tags: ['board', 'qa'],
      labels: ['is-label-a'],
      metrics: { comments: 6, attachments: 2 },
    },
    'task-6': {
      id: 'task-6',
      code: 'ELV-104',
      title: 'Presence heartbeat for online teammates',
      priority: 'Medium',
      assigneeName: 'Sam Taylor',
      tags: ['presence'],
      checklists: { done: 3, total: 3 },
    },
    'task-7': {
      id: 'task-7',
      code: 'ELV-101',
      title: 'Normalize Google avatar URLs through server origin',
      priority: 'High',
      dueDate: 'May 22',
      assigneeName: 'Maya Kim',
      tags: ['auth', 'avatar'],
      metrics: { attachments: 1 },
    },
    'task-8': {
      id: 'task-8',
      code: 'ELV-97',
      title: 'OpenAPI spec generated from Zod routes',
      priority: 'Medium',
      assigneeName: 'Alex Reed',
      tags: ['api', 'docs'],
      labels: ['is-label-b'],
      checklists: { done: 4, total: 6 },
    },
    'task-9': {
      id: 'task-9',
      code: 'ELV-92',
      title: 'Polish task detail sidebar due-date states',
      priority: 'Low',
      dueDate: 'Yesterday',
      dueStatus: 'overdue',
      tags: ['tasks', 'ui'],
      metrics: { comments: 2 },
    },
    'task-10': {
      id: 'task-10',
      code: 'ELV-88',
      title: 'Workspace invite accept / reject flow',
      priority: 'High',
      assigneeName: 'Maya Kim',
      tags: ['workspace'],
      checklists: { done: 5, total: 5 },
    },
    'task-11': {
      id: 'task-11',
      code: 'ELV-82',
      title: 'Seed demo workspace on first boot',
      priority: 'Low',
      assigneeName: 'Alex Reed',
      tags: ['seed'],
    },
    'task-12': {
      id: 'task-12',
      code: 'ELV-77',
      title: 'Keep generated docs portal in sync with API changes',
      priority: 'Medium',
      tags: ['docs', 'release'],
      metrics: { comments: 1, attachments: 1 },
    },
  },
};
